DROP TABLE IF EXISTS book;
CREATE TABLE book (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    isbn VARCHAR(255) UNIQUE NOT NULL,
    author VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    price NUMERIC(14, 4) NOT NULL
    version BIGINT NOT NULL
)